[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Access-Control-Allow-Origin = "*"
